import type { ClientRecord } from "@/types/mock";

const recurringSummaries = {
  "Aguardando contato": "Cliente relata instabilidade frequente em celulares e TV e precisa de novo retorno da equipe.",
  "O.S. aberta": "Caso recorrente já encaminhado para vistoria local, aguardando conclusão do técnico em campo.",
  Resolvido: "Atendimento concluído com orientação ao cliente e estabilização do cenário encontrado no local.",
  "Sem retorno": "Contato tentado pela equipe, porém sem retorno do cliente para continuidade do atendimento.",
} as const;

function daysAgo(days: number, hour: number, minute: number) {
  const date = new Date();
  date.setDate(date.getDate() - days);
  date.setHours(hour, minute, 0, 0);
  return date.toISOString();
}

export const assigneeOptions = ["Felipe", "Bruna", "Marcos", "Camila", "Equipe Campo", "Supervisão"];

export const initialClients: ClientRecord[] = [
  {
    id: "cli-001",
    name: "Rosilene Souza Zampieri",
    phone: "553484128606",
    totalServices: 14,
    description: recurringSummaries["Aguardando contato"],
    status: "Aguardando contato",
    assignee: "Felipe",
    osOpen: false,
    osNumber: "",
    resolved: false,
    notes: "Cliente recorrente e sensível ao atendimento; priorizar retorno com clareza.",
    updatedAt: daysAgo(0, 10, 22),
  },
  {
    id: "cli-002",
    name: "Cristina Alves",
    phone: "553491868167",
    totalServices: 12,
    description: recurringSummaries["O.S. aberta"],
    status: "O.S. aberta",
    assignee: "Bruna",
    osOpen: true,
    osNumber: "OS-2401",
    resolved: false,
    notes: "Necessária vistoria local após múltiplos relatos sobre oscilação no período noturno.",
    updatedAt: daysAgo(0, 9, 48),
  },
  {
    id: "cli-003",
    name: "Eliete Maria Duarte",
    phone: "553498026667",
    totalServices: 11,
    description: recurringSummaries["Sem retorno"],
    status: "Sem retorno",
    assignee: "Marcos",
    osOpen: false,
    osNumber: "",
    resolved: false,
    notes: "Aguardando cliente retornar com dados para continuidade.",
    updatedAt: daysAgo(4, 15, 13),
  },
  {
    id: "cli-004",
    name: "Sizina Teresa Santos De Siqueira",
    phone: "553497419906",
    totalServices: 11,
    description: recurringSummaries.Resolvido,
    status: "Resolvido",
    assignee: "Equipe Campo",
    osOpen: true,
    osNumber: "OS-2393",
    resolved: true,
    notes: "Ajuste finalizado e cliente orientado sobre cenário local.",
    updatedAt: daysAgo(1, 14, 5),
  },
  {
    id: "cli-005",
    name: "Keiziane Alves Da Gama",
    phone: "553497096970",
    totalServices: 10,
    description: recurringSummaries["Aguardando contato"],
    status: "Aguardando contato",
    assignee: "Camila",
    osOpen: false,
    osNumber: "",
    resolved: false,
    notes: "Retornar preferencialmente pela manhã.",
    updatedAt: daysAgo(0, 8, 15),
  },
  {
    id: "cli-006",
    name: "Luiz Carlos Da Silva Pereira",
    phone: "553498678992",
    totalServices: 10,
    description: recurringSummaries["O.S. aberta"],
    status: "O.S. aberta",
    assignee: "Bruna",
    osOpen: true,
    osNumber: "OS-2388",
    resolved: false,
    notes: "Cliente informou piora após chuvas; validar infra local.",
    updatedAt: daysAgo(1, 17, 40),
  },
  {
    id: "cli-007",
    name: "JULIO CESAR SILVA ARAUJO",
    phone: "553498890383",
    totalServices: 10,
    description: recurringSummaries["Aguardando contato"],
    status: "Aguardando contato",
    assignee: "Felipe",
    osOpen: false,
    osNumber: "",
    resolved: false,
    notes: "Cliente já recusou suporte remoto anteriormente.",
    updatedAt: daysAgo(1, 17, 2),
  },
  {
    id: "cli-008",
    name: "Frank Bitencurt De Souza",
    phone: "553499782809",
    totalServices: 10,
    description: recurringSummaries["Sem retorno"],
    status: "Sem retorno",
    assignee: "Marcos",
    osOpen: false,
    osNumber: "",
    resolved: false,
    notes: "Fazer nova tentativa via WhatsApp antes de escalar.",
    updatedAt: daysAgo(3, 16, 55),
  },
  {
    id: "cli-009",
    name: "Cristiano Henrique Venancio Junior",
    phone: "553498653995",
    totalServices: 10,
    description: recurringSummaries.Resolvido,
    status: "Resolvido",
    assignee: "Equipe Campo",
    osOpen: true,
    osNumber: "OS-2374",
    resolved: true,
    notes: "Cliente permanece em monitoramento leve.",
    updatedAt: daysAgo(1, 16, 30),
  },
  {
    id: "cli-010",
    name: "Paulo Renato Miranda",
    phone: "553499921472",
    totalServices: 9,
    description: recurringSummaries["Aguardando contato"],
    status: "Aguardando contato",
    assignee: "Camila",
    osOpen: false,
    osNumber: "",
    resolved: false,
    notes: "Cliente pediu retorno após 18h.",
    updatedAt: daysAgo(2, 15, 54),
  },
  {
    id: "cli-011",
    name: "Terezinha Aparecida Da Rocha Borges",
    phone: "553499742913",
    totalServices: 9,
    description: recurringSummaries["Sem retorno"],
    status: "Sem retorno",
    assignee: "Marcos",
    osOpen: false,
    osNumber: "",
    resolved: false,
    notes: "Sem sucesso no contato desde a última atualização.",
    updatedAt: daysAgo(5, 15, 8),
  },
  {
    id: "cli-012",
    name: "Fernanda Silva De Melo",
    phone: "553498830601",
    totalServices: 9,
    description: recurringSummaries["O.S. aberta"],
    status: "O.S. aberta",
    assignee: "Bruna",
    osOpen: true,
    osNumber: "OS-2369",
    resolved: false,
    notes: "Técnico agendado para vistoria no local.",
    updatedAt: daysAgo(2, 14, 32),
  },
  {
    id: "cli-013",
    name: "Fabiana Ferreira Melo",
    phone: "553492859314",
    totalServices: 9,
    description: recurringSummaries.Resolvido,
    status: "Resolvido",
    assignee: "Equipe Campo",
    osOpen: true,
    osNumber: "OS-2362",
    resolved: true,
    notes: "Caso finalizado sem novas pendências.",
    updatedAt: daysAgo(2, 14, 5),
  },
  {
    id: "cli-014",
    name: "Madalena Das Gracas Silva",
    phone: "553499629070",
    totalServices: 9,
    description: recurringSummaries["Aguardando contato"],
    status: "Aguardando contato",
    assignee: "Felipe",
    osOpen: false,
    osNumber: "",
    resolved: false,
    notes: "Retorno em aberto para coleta de mais detalhes.",
    updatedAt: daysAgo(2, 13, 44),
  },
  {
    id: "cli-015",
    name: "Luiz Fernando Silva",
    phone: "553484265730",
    totalServices: 9,
    description: recurringSummaries["Sem retorno"],
    status: "Sem retorno",
    assignee: "Marcos",
    osOpen: false,
    osNumber: "",
    resolved: false,
    notes: "Cliente ainda não retornou após nova tentativa de contato.",
    updatedAt: daysAgo(6, 13, 18),
  },
  {
    id: "cli-016",
    name: "Leidimar De Fatima Coura Macedo",
    phone: "553499745317",
    totalServices: 9,
    description: recurringSummaries["O.S. aberta"],
    status: "O.S. aberta",
    assignee: "Bruna",
    osOpen: true,
    osNumber: "OS-2354",
    resolved: false,
    notes: "Acompanhar retorno do técnico de campo.",
    updatedAt: daysAgo(2, 12, 56),
  },
  {
    id: "cli-017",
    name: "Jayma Thallyne Silva Ferreira",
    phone: "553497650378",
    totalServices: 9,
    description: recurringSummaries["Aguardando contato"],
    status: "Aguardando contato",
    assignee: "Camila",
    osOpen: false,
    osNumber: "",
    resolved: false,
    notes: "Cliente prefere contato via WhatsApp.",
    updatedAt: daysAgo(1, 12, 20),
  },
  {
    id: "cli-018",
    name: "Michelle Marques Meireles Alves",
    phone: "553484261642",
    totalServices: 9,
    description: recurringSummaries.Resolvido,
    status: "Resolvido",
    assignee: "Equipe Campo",
    osOpen: true,
    osNumber: "OS-2348",
    resolved: true,
    notes: "Caso resolvido e cliente orientado sobre boas práticas de uso.",
    updatedAt: daysAgo(1, 11, 43),
  },
  {
    id: "cli-019",
    name: "Eliete Maria Duarte",
    phone: "553496330591",
    totalServices: 9,
    description: recurringSummaries["Sem retorno"],
    status: "Sem retorno",
    assignee: "Marcos",
    osOpen: false,
    osNumber: "",
    resolved: false,
    notes: "Duplicidade de nome na base; conferir titular antes de prosseguir.",
    updatedAt: daysAgo(4, 11, 4),
  },
  {
    id: "cli-020",
    name: "Domingos",
    phone: "553484406892",
    totalServices: 9,
    description: recurringSummaries["Aguardando contato"],
    status: "Aguardando contato",
    assignee: "Felipe",
    osOpen: false,
    osNumber: "",
    resolved: false,
    notes: "Cliente entrou recentemente para monitoramento recorrente.",
    updatedAt: daysAgo(3, 10, 31),
  },
];
